### PR TITLE
Improve dev experience and webpack config

### PR DESCRIPTION
**Pull request by nicksellen**
Quite a load of stuff here:
- use import over require
- use DefinePlugin over htmlWebpackPlugin.options in templates
- put more webpack config into base
- fix invalid html in index.html template
- add dev server with watching and hot reloading
- seperate webpack shims into own file
- add production-ready webpack builds (uglify etc)
- add commons chunk configuration (maybe not optimal yet)
- add prettier and npm run format for js formatting
- switch everything to npm (instead of yarn)
  (only dev/ directory for now)
- support loading frontend routes from dev server
- improve WEBPACK.md docs

@edwh I'm not sure how this fits into your development environment (phpstorm, etc), so we might need to work with that a bit.

This _should_ now work that a dev can run `npm install && npm run dev` and be up and running for frontend dev (I just tried it on a fresh clone and it worked).

I also introduced `prettier` for js formatting, `npm run format` will auto format all the code in `dev/*` (not the whole codebase yet).

This is still WIP as I haven't addressed:
* template loading via webpack
* modtools builds vs main site builds
* probably some other stuff (tired now)

### CODE REVIEW

**Comment by nicksellen** [comment]
Ok, template loading works :)

It's basically just this... 

```js
return import(
    /* webpackMode: "lazy-once" */
    '/template/' + templatePath
).then(function(html){
// ...
```

The `lazy-once` is what makes it bundle them all together in one file.

I also added a babel compilation step, this means we can use modern javascript features that get compiled to browser compatible javascript. Which browsers are meant to be supported? (I set it to `"> 1%", "last 2 versions"` see `.babelrc`, options are available [here](https://github.com/ai/browserslist)).

I also added an eslint configuration which you can try out with either `npm run lint` or install an eslint plugin in your editor. At the moment I just set it to give a warning on undefined variables. Currently it catches a few errors (e.g. `FACEBOOK_APP_ID` instead of `FACEBOOK_APPID`), but most of the warnings are due to not declaring variables (`a = 'foo'` instead of `var a = 'foo'`) which I _think_ will always cause an error in browsers (as strict mode is enabled from the babel step). I fixed a few of them that I saw in my browser, but I think eslint is able to show all the others.

(and a vuejs component is available in the webpack-vue branch).

Next steps for me are understanding more about modtools, I realised I don't really know enough about it to think about the best approach. Although I think a good approach might be adding two webpack entries (currently we just have `client/app.js` but could have `client/modtools.js`), but that doesn't address the different site variables. Most of them seem to just be set to the hostname of the site is being served from so maybe can be removed anyway.

**Comment by edwh** [comment]
Brief replies in line from phone. 

On 3 December 2017 12:48:43 CET, Nick Sellen <notifications@github.com> wrote:
>Ok, template loading works :)
>
>It's basically just this... 
>
>```js
>return import(
>    /* webpackMode: "lazy-once" */
>    '/template/' + templatePath
>).then(function(html){
>// ...
>```
>
>The `lazy-once` is what makes it bundle them all together in one file.
>

OK. May need to split for performance based on previous experience but it's a start. 

>I also added a babel compilation step, this means we can use modern
>javascript features that get compiled to browser compatible javascript.

OK. 

>Which browsers are meant to be supported? (I set it to `"> 1%", "last 2
>versions"` see `.babelrc`, options are available
>[here](https://github.com/ai/browserslist)).
>

Probably 5% in UK if you can do that. For example I think we currently support IE8. Given our purpose we need to be friendly to older devices. 

>I also added an eslint configuration which you can try out with either
>`npm run lint` or install an eslint plugin in your editor. At the
>moment I just set it to give a warning on undefined variables.
>Currently it catches a few errors (e.g. `FACEBOOK_APP_ID` instead of
>`FACEBOOK_APPID`), but most of the warnings are due to not declaring
>variables (`a = 'foo'` instead of `var a = 'foo'`) which I _think_ will
>always cause an error in browsers (as strict mode is enabled from the
>babel step). I fixed a few of them that I saw in my browser, but I
>think eslint is able to show all the others.
>

I would prefer to see the warnings and not have a browser error, otherwise we need to fix them all before we can go live.

>(and a vuejs component is available in the webpack-vue branch).
>
>Next steps for me are understanding more about modtools, I realised I
>don't really know enough about it to think about the best approach.
>Although I think a good approach might be adding two webpack entries
>(currently we just have `client/app.js` but could have
>`client/modtools.js`), but that doesn't address the different site
>variables. Most of them seem to just be set to the hostname of the site
>is being served from so maybe can be removed anyway.

Key differences are logo, style sheet, flag that gets passed around in an option to views. 

Would be good to have MT and FD templates and code separate bundles so that users don't have to load that code.

**Comment by nicksellen** [comment]
I added a single e2e test using testcafe https://devexpress.github.io/testcafe/ docs available in `tests/e2e/README.md`.

> I would prefer to see the warnings and not have a browser error, otherwise we need to fix them all before we can go live.

We can use a different babel configuration to make it not error, but it's actually very nice to have strict mode enabled, and I _think_ the eslint config is catching them all, there are 89 left (but only about 10 variables). Have a look when you get back to the computer proper, there are some actual errors there by the looks of it.

> IE8

I added an `ie >= 8`

I think it's not _quite_ as simple as just putting that, will need some manual testing.

**Comment by edwh** [comment]
On 3 December 2017 13:58:23 CET, Nick Sellen <notifications@github.com> wrote:
>I added a single e2e test using testcafe
>https://devexpress.github.io/testcafe/ docs available in
>`tests/e2e/README.md`.
>
>> I would prefer to see the warnings and not have a browser error,
>otherwise we need to fix them all before we can go live.
>
>We can use a different babel configuration to make it not error, but
>it's actually very nice to have strict mode enabled, and I _think_ the
>eslint config is catching them all, there are 89 left (but only about
>10 variables). Have a look when you get back to the computer proper,
>there are some actual errors there by the looks of it.
>

OK, that's a manageable number. 

>> IE8
>
>I added an `ie >= 8`
>
>I think it's not _quite_ as simple as just putting that, will need some
>manual testing.

OK.

**Comment by nicksellen** [comment]
> Key differences are logo, style sheet, flag that gets passed around in an option to views. Would be good to have MT and FD templates and code separate bundles so that users don't have to load that code.

I _think_ the best approach will be multiple webpack builds. There are two tools to help building multiple webpack outputs [parallel-webpack](https://github.com/trivago/parallel-webpack) and [webpack-cluster](https://github.com/Fitbit/webpack-cluster).

They would vary by having different values set in the `DefinePlugin`'s, and have a different entrypoint, but otherwise could be the same.

One of the advantages of this method is you can use `DefinePlugin` to define `MODTOOLS = true|false` then anywhere in the code have `if (MODTOOLS) { doOneThing() } else { doAnotherThing }`.. at build time it will turn into either `doOneThing()` or `doAnotherThing()` (as `MODTOOLS` will be replaced with `true|false`, then uglify will notice the unreachable code, and remove it), so the clientside just have the final verison of the code and not have to do any logic at runtime.

Does that sound like it would work? Still not entirely sure how modtools is used/deployed/etc.

**Comment by nicksellen** [comment]
... the other aspect being the development flow, are you normally working on one or the other? or do you work on them at the same time?

**Comment by nicksellen** [comment]
I think ie8 is going to be painful/impossible. Both React and Vue only support IE9 and above. Webpack >= 2 does not support ie8 either (https://github.com/webpack/webpack/issues/3070).

**Comment by edwh** [comment]
That sounds fine. I didn't want to split it out if that was stupid for some reason. 

I usually work on one or the other.

**Comment by edwh** [comment]
We can probably live without IE8 - I was using it as an example because last two versions seems a bit harsh.

I have one particular volunteer on an old version of Firefox. I'll check which.

**Comment by nicksellen** [comment]
> We can probably live without IE8 - I was using it as an example because last two versions seems a bit harsh.

Yeah, the "> 1%" should mean it handles a lot more. Can you sign up for https://saucelabs.com/open-source? It works nicely with testcafe, then we can actually run stuff on them.

**Comment by edwh** [comment]
The version of Firefox I mentioned is 47.0.2, which is pretty old, but the volunteer in question won't upgrade because they will lose an extension they like. What's the minimum version of Firefox for webpack 2? 

Of course, we could make the extension work...

**Comment by nicksellen** [comment]
Oh, I'm sure Firefox 47 is fine, it's from June 7, 2016. ie8 is from 2009...

**Comment by nicksellen** [comment]
I also just got the testcafe tests running in circleci (on my fork). It runs up the frontend and looks for a table in Bath :) ... it uses https://dev.ilovefreegle.org, so if there are no tables available in Bath, the test will fail. To be improved....

If you add me to Freegle github org I can set it up on there, or if you'd rather not, I can walk you through how to set it up.

**Comment by edwh** [comment]
Happy to add you, though just on my phone, so it may need to wait till I get back. I'll see.

**Comment by edwh** [comment]
Not sure I can do this until we split the client into its own 
repository.  It says:


------ Original Message ------

**Comment by nicksellen** [comment]
Maybe make the saucelabs as a separate issue? If it's free for all open source then doesn't matter about waiting for repo. Can have both!

**Comment by edwh** [comment]
(Opinionated reply warning)

I am a bit sceptical of the value of this kind of test which works based 
on looking for DOM elements and faking events on them.  When I've done 
them before, they end up basically testing that backbone works - the way 
things are broken down into views with events means that stuff tends to 
just work, and it's relatively hard to break one view when working on 
another.  They don't do much to test some of the more easily easily 
broken and more important stuff like "looks rubbish on mobile", and they 
focus very much on what you expect to happen functionally but not much 
on what appears on the screen - for example all the images and 
stylesheets could fail to load and most tests would still pass.

So the PHPUnit tests are an absolute godsend, and during the development 
I had 100% code coverage (it will have dropped).  If I had very much 
genuine logic in the JS code I would absolutely want to have equivalent 
tests.  But for what is basically rendering and click handling, I find 
it ends up costing me a lot more maintenance time than it saves in 
spotting bugs.  So I rely much more on the human testing that we get 
from our volunteers.  All that basically means I wouldn't mind someone 
else writing and maintaining them - but I'm quite unlikely to do that 
myself.

I could be wrong - for example, if you showed me an example of a device 
specific bug that was spotted as a consequence of running the same test 
easily across many devices.  Persuade me.

------ Original Message ------

**Comment by nicksellen** [comment]
Not sure why are discussing in this closed PR thread, but hey ho :)

There are a bunch of things that can go wrong between what you get with "npm run dev" and the final bundled files. e2e tests makes sure it at least _basically works_.

For new contributors it ensures someone hasn't fundamentally broken the entire site (easily possible I think, change one little webpack plugin only use in production...).

And provides a basic sanity check that it works in _a_ real browser (chrome/firefox headless), and also (via saucelabs) makes sure that it basically works in some older browsers that no dev would have installed (webpack bundling / babel might use some js features even if you don't use them directly in the app js code).

> They don't do much to test some of the more easily easily broken and more important stuff like "looks rubbish on mobile", and they focus very much on what you expect to happen functionally but not much on what appears on the screen - for example all the images and stylesheets could fail to load and most tests would still pass.

"looks rubbish on mobile" isn't really a testing concern, although testcafe can take screenshots... so _should_ actually be possible to use it to generate a matrix of views/browsers and publish it somewhere to easily view.

They might add support for "element in viewpoint" later, which can check the element has wrapped off the page somewhere.

It's also quite flexible so here's a test someone has written to check if all the images are present https://stackoverflow.com/a/46831540.

> I find it ends up costing me a lot more maintenance time than it saves in spotting bugs

I agree e2e tests have this problem, selectors change over time, and they can be flakey with timing. Although testcafe is quite good with waiting for elements to appear by default. But I'm not proposing the e2e suite become comprehensive, just capture a few key flows (find something not logged in, signup, login, post item kind of thing). I would intend to add unit tests for the frontend too.

They also don't replace human testing anyway, it's just extra stuff, so between linting, unit tests, e2e tests, and manual human testing should be possible to keep/improve quality nicely :)

**Pull request merged**
